Repository serghey-rodin/vesta, pull requests merged in 2018-11, with the labels that each got.

#1781 Fix quotes in cronjob CMD
  web/edit/cron/index.php
Labels: bug, confirmed

#1666 Fix editing backup exclusions
  bin/v-backup-user
Labels: awaiting information, bug

#1733 supose fix to #1526
  bin/v-update-user-counters
Labels: bug

#1696 bugfix nginx templates
  install/ubuntu/12.04/templates/web/nginx/http2.stpl
  install/ubuntu/12.04/templates/web/nginx/http2.tpl
  install/ubuntu/12.10/templates/web/nginx/http2.stpl
  install/ubuntu/12.10/templates/web/nginx/http2.tpl
  install/ubuntu/13.04/templates/web/nginx/http2.stpl
  install/ubuntu/13.04/templates/web/nginx/http2.tpl
  install/ubuntu/13.10/templates/web/nginx/http2.stpl
  install/ubuntu/13.10/templates/web/nginx/http2.tpl
  install/ubuntu/14.04/templates/web/nginx/http2.stpl
  install/ubuntu/14.04/templates/web/nginx/http2.tpl
  install/ubuntu/14.10/templates/web/nginx/http2.stpl
  install/ubuntu/14.10/templates/web/nginx/http2.tpl
  install/ubuntu/15.04/templates/web/nginx/http2.stpl
  install/ubuntu/15.04/templates/web/nginx/http2.tpl
  install/ubuntu/15.10/templates/web/nginx/http2.stpl
  install/ubuntu/15.10/templates/web/nginx/http2.tpl
  install/ubuntu/16.04/templates/web/nginx/http2.stpl
  install/ubuntu/16.04/templates/web/nginx/http2.tpl
  install/ubuntu/16.10/templates/web/nginx/http2.stpl
  install/ubuntu/16.10/templates/web/nginx/http2.tpl
  install/ubuntu/17.04/templates/web/nginx/http2.stpl
  install/ubuntu/17.04/templates/web/nginx/http2.tpl
  install/ubuntu/17.10/templates/web/nginx/http2.stpl
  install/ubuntu/17.10/templates/web/nginx/http2.tpl
  install/ubuntu/18.04/templates/web/nginx/caching.stpl
  install/ubuntu/18.04/templates/web/nginx/default.stpl
  install/ubuntu/18.04/templates/web/nginx/hosting.stpl
  install/ubuntu/18.04/templates/web/nginx/http2.stpl
  install/ubuntu/18.04/templates/web/nginx/http2.tpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/cms_made_simple.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/codeigniter2.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/codeigniter3.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/datalife_engine.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/default.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/dokuwiki.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/drupal6.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/drupal7.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/drupal8.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/joomla.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/laravel.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/magento.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/modx.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/moodle.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/no-php.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/odoo.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/opencart.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/owncloud.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/piwik.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/pyrocms.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/wordpress.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/wordpress2.stpl
  install/ubuntu/18.04/templates/web/nginx/php-fpm/wordpress2_rewrite.stpl
Labels: enhancement
