Repository serghey-rodin/vesta, pull requests merged in 2021-08, with the labels that each got.

#1978 Fix issue #1977 / Letsencrypt ssl certificate update fails
  bin/v-delete-web-domain-ssl
Labels: Solved, bug, confirmed

#1826 fix backend_template save after package change
  bin/v-change-user-package
  bin/v-list-user-package
Labels: bug, confirmed

#1799 Setting lets encrypt hostname ssl auto-renewal during install
  install/vst-install-amazon.sh
  install/vst-install-debian.sh
  install/vst-install-rhel.sh
  install/vst-install-ubuntu.sh
Labels: feature request, installer, on a testing
